### ISSUE TITLE
Link to installation manual in the README doesn't exist

### ISSUE THREAD

**Issue by rikedia** [Stanford-Online/xblock-free-text-response#13]
The link to the installation manual in the README doesn't exist (https://github.com/Stanford-Online/xblock-free-text-response@cfb793db182b60281875b83b53a98640d740ebcf#egg=xblock-free-text-response).

**Comment by stvstnfrd** [comment]
@rikedia That is just a sample (hence the `e.g.`) and is only meant to demonstrate the syntax.
The actual version that you install is up to you.
