### ISSUE TITLE
Students will not be able to access this component. Re-edit your component to fix the error.  Error: freetextresponse_view.html

### ISSUE THREAD

**Issue by MamlukiSn** [Stanford-Online/xblock-free-text-response#23]
Hi,

I'm getting the error above  when trying to use Free-text Response XBlock from studio. This applies to release/v0.1.6 and release/v0.1.7.  Currently running a native installation on ficus.

Log from the cms show
 `
Traceback (most recent call last):
  File "/edx/app/edxapp/edx-platform/cms/djangoapps/contentstore/views/preview.py", line 304, in get_preview_fragment
    fragment = module.render(preview_view, context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/core.py", line 193, in render
    return self.runtime.render(self, view, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1889, in render
    return self.__getattr__('render')(block, view_name, context)
  File "/edx/app/edxapp/edx-platform/common/lib/xmodule/xmodule/x_module.py", line 1297, in render
    return super(MetricsMixin, self).render(block, view_name, context=context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/xblock/runtime.py", line 806, in render
    frag = view_fn(context)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/freetextresponse/freetextresponse.py", line 272, in student_view
    template = get_template('freetextresponse_view.html')
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/django/template/loader.py", line 46, in get_template
    raise TemplateDoesNotExist(template_name)
TemplateDoesNotExist: freetextresponse_view.html
`

**Comment by mrik974** [comment]
Hi. Stumbled into the same issue. The problem probably comes from the `setup.py` file that doesn't copy the template into the right place. What I did was just copy the file named `"freetextresponse_view.html"` (which you can find [here](https://github.com/Stanford-Online/xblock-free-text-response/blob/master/freetextresponse/templates/freetextresponse_view.html)) to `/edx/app/edxapp/edx-platform/common/templates`
A cleaner solution would be welcome though, but I'm not confident enough in python (don't even talk about django) to provide it.

**Comment by stvstnfrd** [comment]
Hi @mrik974 @MamlukiSn !

I think we've figured out the issue here.
This looks to have happened when we updated this XBlock to start using Django Templates.

You'll need to add `freetextresponse` to your `INSTALLED_APPS` in the django settings.

Making that change will allow the system to find the template w/in the XBlock.

Let us know if you have any questions!

**Comment by mrik974** [comment]
Hi @stvstnfrd 
Thank you for your answer. What django settings file are you talking about ? Are there other steps to make it work ?
I've found 2 settings files located at : 
- `edx-platform/lms/envs/common.py`
- `edx-platform/cms/envs/common.py`

Adding `freetextresponse` to the `INSTALLED_APPS` setting doesn't seem to fix the error.

**Comment by stvstnfrd** [comment]
Following the sunset of the Lagunita project, this repo lives on under edx's stewardship at:
- https://github.com/edx/xblock-free-text-response

This should have support through master/Juniper already.
