### ISSUE TITLE
Can we use this as the Apache License?

### ISSUE THREAD

**Issue by yokose-ks** [Stanford-Online/xblock-free-text-response#28]
Hi,

We're thinking that we would like use this XBlock in production.
But, I could not find any license in this repository.
Can we use this as the Apache License in the same manner as other XBlocks?

Thanks in advance.

**Comment by stvstnfrd** [comment]
Hi @yokose-ks .

We've updated the repository to reflect the AGPLv3 license that we use on other XBlocks.

Thanks!

**Comment by yokose-ks** [comment]
@stvstnfrd ,

Thank you very much for your prompt reply and repository update.
We understand this is under AGPLv3, and that's fine with us.
