### ISSUE TITLE
Ginkgo-compatible version of FreeTextResponseXBlock?

### ISSUE THREAD

**Issue by itsjeyd** [Stanford-Online/xblock-free-text-response#45]
Hi everyone,

Is there a version/release of this XBlock that is known to be compatible/working with the Ginkgo release of edx-platform?

Based on the [release history](https://github.com/Stanford-Online/xblock-free-text-response/releases) I was assuming that [v0.3.1](https://github.com/Stanford-Online/xblock-free-text-response/tree/release/v0.3.1) would be compatible (as it's the latest version before the release containing compatibility updates for Hawthorn), but found that it was not working when installing it on an Open edX instance running Ginkgo. (Studio was unable to render the XBlock after adding it to a unit.)

If you could point me towards a release (or commit) that should be used for Ginkgo installations of Open edX, that would be great.

Thanks!

**Comment by pomegranited** [comment]
@dcadams Is this something you can help us with?

**Comment by stvstnfrd** [comment]
Following the sunset of the Lagunita project, this repo lives on under edx's stewardship at:
- https://github.com/edx/xblock-free-text-response

This should have support through master/Juniper already.
